package giuliacrepaldi.enumeration;

public enum Genere {
    ROMANZO, FANTASCIENZA, FANTASY, GIALLO, THRILLER, HORROR, STORICO, BIOGRAFIA, SAGGISTICA, AVVENTURA, POESIA, CLASSICO, TECNICO_SCIENTIFICO
}
